apiVersion: apps/v1
kind: Deployment
metadata:
  name: xt37-playlist-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xt37-playlist-recommender
  template:
    metadata:
      labels:
        app: xt37-playlist-recommender
    spec:
      containers:
      - name: michelletian1104/frontend_container
        image: app:latest
        ports:
        - containerPort: 30506
