apiVersion: apps/v1
kind: Deployment
metadata:
  name: xt37-recommender-deployment-v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: xt37-playlist-recommender
  template:
    metadata:
      labels:
        app: xt37-playlist-recommender
    spec:
      containers:
        - name: deployment-container
          image: michelletian1104/frontend:v2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "1Gi"
          ports:
            - containerPort: 30506
          volumeMounts:
            - name: xt37-recommender-deployment
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: xt37-recommender-deployment
          persistentVolumeClaim:
            claimName: project2-pvc-xt37