apiVersion: v1
kind: Deployment
metadata:
  name: xt37-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt37-playlist-recommender
  template:
    metadata:
      labels:
        app: xt37-playlist-recommender
    spec:
      containers:
        - name: deployment-container
          image: michelletian1104/frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "1Gi"
          ports:
            - containerPort: 30506
          volumeMounts:
            - name: xt37-recommender-deployment
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: xt37-recommender-deployment
          persistentVolumeClaim:
            claimName: xt37-recommender-pvc
