apiVersion: v1
kind: Deployment
metadata:
  name: xt37-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt37-playlist-recommender
  template:
    metadata:
      labels:
        app: xt37-playlist-recommender
    spec:
      containers:
      - name: deployment-container
        image: michelletian1104/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30506
      restartPolicy: Always
