apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: xt37
  name: project2-pvc-xt37
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv-xt37
  storageClassName: standard
